services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
      - redis


#  nginx:
#    image: nginx:latest
#    container_name: nginx_server
#    ports:
#      - "8000:80"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    depends_on:
#      - web

  db:
    image: postgres:13-bullseye
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: on-failure

volumes:
  postgres_data: