services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/app
    networks:
      - my_network
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx_server
    networks:
      - my_network
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  db:
    image: postgres:13-bullseye
    container_name: postgres_db
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: