FROM python:3.12-slim

WORKDIR /app

# Install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    libjpeg62 \
    zlib1g \
    libmagic1 \
    netcat-traditional \
    dos2unix \
 && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn

COPY . .

# Ensure entrypoint scripts have Unix-style line endings and are executable
RUN dos2unix /app/entrypoint_telegram.sh && chmod +x /app/entrypoint_telegram.sh

# Default entrypoint for Django
ENTRYPOINT ["/app/entrypoint_telegram.sh"]
