
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/app
    expose:
      - "8000"
    command: "bash entrypoint.sh"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  db:
    image: postgres:13-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres
    expose:
      - 5432
    ports:
      - target: 5432
        published: 2345
        protocol: tcp
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: on-failure

  redis:
    image: redis
    restart: always

volumes:
  postgres_data: