services:
  web:
    image: mini_dice_image
    container_name: django_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=miniDice.settings
    networks:
      - dev_network
    depends_on:
      - db
      - redis

  telegbot:
    image: mini_dice_telegram_image
    container_name: telegram_bot_run
    build:
      context: .
      dockerfile: Dockerfile_telegram
    volumes:
      - .:/app
    env_file:
      - ./.env
    networks:
      - dev_network
    depends_on:
      - web
      - db
      - redis

  db:
    image: postgres:latest
    container_name: dev-db
    ports:
      - "5432:5432" # Expose PostgreSQL port
    volumes:
      - ../volumes/postgres_dev_data:/var/lib/postgresql/data # Use volumes directory for persistent data
    env_file:
      - ./.env
    networks:
      - dev_network

  redis:
    image: redis:latest
    container_name: dev-redis
    ports:
      - "6379:6379" # Expose Redis port
    volumes:
      - ../volumes/redis_dev_data:/data # Use volumes directory for persistent data
    env_file:
      - ./.env
    networks:
      - dev_network

  dashboard:
    image: mini_dice_dashboard
    container_name: dev-dashboard
    ports:
      - "8501:8501"
    env_file:
      - ./dashboard/.env
    networks:
      - dev_network

volumes:
  postgres_data:
    driver: local

  redis_dev_data:
    driver: local

networks:
  dev_network: