services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait_for_db.sh", "db", "gunicorn", "project_name.wsgi:application", "--bind", "0.0.0.0:8000"]
    networks:
      - app_network
    container_name: django_app
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=miniDice.settings


  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app_network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

networks:
  app_network:

volumes:
  postgres_data: