# Generated by Django 5.1.5 on 2025-03-02 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_alter_referral_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='insert time')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.player')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
            },
        ),
    ]
