# Generated by Django 5.1.5 on 2025-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='decimal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
