# Generated by Django 5.1.5 on 2025-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
