# Generated by Django 5.1.5 on 2025-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='master_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=24, max_digits=56, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='decimal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
