# Generated by Django 5.1.5 on 2025-03-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_master_address_asset_name_asset_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='usd_value',
            field=models.DecimalField(blank=True, decimal_places=24, max_digits=56, null=True),
        ),
    ]
