# Generated by Django 5.1.5 on 2025-01-26 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='insert time')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('expire_dt', models.DateTimeField()),
                ('dice_number1', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('dice_number2', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'CountDownResult',
                'verbose_name_plural': 'CountDownResults',
                'db_table': 'countdown_result',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='insert time')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('telegram_username', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('telegram_language_code', models.CharField(default='en', max_length=16)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='insert time')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('dice_number1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('dice_number2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('is_win', models.BooleanField(default=False)),
                ('countdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='user.countdown')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.player')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'db_table': 'prediction',
            },
        ),
    ]
