# Generated by Django 5.1.5 on 2025-02-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_player_first_name_alter_player_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wallet_insert_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
