# Generated by Django 5.1.5 on 2025-02-06 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_player_wallet_insert_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='predict_slot',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(21)]),
        ),
        migrations.AddField(
            model_name='player',
            name='referral_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='slot',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(21)]),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='user.player'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='insert time')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('referee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='user.player')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
