# Generated by Django 5.1.5 on 2025-02-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_player_predict_slot_player_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='has_end',
            field=models.BooleanField(default=False),
        ),
    ]
