# Generated by Django 5.1.5 on 2025-02-21 16:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_countdown_has_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='predict_slot',
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('insert_dt', models.DateTimeField(auto_now_add=True, verbose_name='insert time')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(21)])),
                ('countdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.countdown')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.player')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'db_table': 'slot',
            },
        ),
    ]
